/**
 * Official list of Secondary Health Care Facilities in Akwa Ibom State
 * Source: Ministry of Health facility register
 *
 * Enrollment lifecycle:
 *   pending            → listed, no credentials yet
 *   credentials_issued → Commissioner (via M87) generated Hospi OS logins
 *   active             → facility used those logins / enrolled Hospi OS → streams live telemetry
 */

export type FacilityEnrollmentStatus = 'pending' | 'credentials_issued' | 'active';

export type FacilityTierLocal =
  | 'national_referral'
  | 'regional_general'
  | 'district_hospital'
  | 'cottage_hospital'
  | 'specialized_center'
  | 'comprehensive_health_centre';

export interface AkwaIbomFacility {
  facilityId: string;
  facilityName: string;
  location: string;
  region: string;
  tier: FacilityTierLocal;
  enrollmentStatus: FacilityEnrollmentStatus;
  /** Generated by Commissioner command via M87 */
  hospiLogin?: string;
  hospiTempPassword?: string;
  credentialsIssuedAt?: string;
  /** Set when facility first authenticates into Hospi OS */
  activatedAt?: string;
  lastSeenAt?: string;
  /** Live telemetry only when active */
  totalBeds?: number;
  occupiedBeds?: number;
  icuBedsTotal?: number;
  icuBedsOccupied?: number;
  ventilatorsAvailable?: number;
  staffOnDuty?: number;
  complianceScore?: number;
  emergencyStatus?: 'normal' | 'surge_code_yellow' | 'surge_code_red' | 'critical';
  licenseNumber?: string;
  licenseExpires?: string;
  accreditationStatus?: 'accredited' | 'provisional' | 'suspended' | 'pending';
}

function inferRegion(location: string, name: string): string {
  const t = `${location} ${name}`.toUpperCase();
  if (t.includes('UYO') || t.includes('ITU') || t.includes('IBESIT') || t.includes('NTO EDINO') || t.includes('MBIAYA'))
    return 'Uyo Region';
  if (t.includes('EKET') || t.includes('ORON') || t.includes('OKOBO') || t.includes('IBENO') || t.includes('EASTERN OBOLO') || t.includes('URUE-OFFONG') || t.includes('ORUKO'))
    return 'Eket Region';
  if (t.includes('IKOT EKPENE') || t.includes('ABAK') || t.includes('ESSEN') || t.includes('UKANA') || t.includes('IKPE') || t.includes('OBOT') || t.includes('EKPENE'))
    return 'Ikot Ekpene Region';
  if (t.includes('ORUK') || t.includes('ANAM') || t.includes('UKANA') || t.includes('IKOT ABASI') || t.includes('MKPAT') || t.includes('EASTERN'))
    return 'Oruk Anam Region';
  return 'Other Regions';
}

function inferTier(name: string): FacilityTierLocal {
  const t = name.toUpperCase();
  if (t.includes('PSYCHIATRIC') || t.includes('INFECTIOUS') || t.includes('LEPROSY')) return 'specialized_center';
  if (t.includes('COTTAGE')) return 'cottage_hospital';
  if (t.includes('COMPREHENSIVE')) return 'comprehensive_health_centre';
  if (t.includes('GENERAL') || t.includes('METHODIST') || t.includes('IMMANUEL') || t.includes('MARY SLESSOR') || t.includes('MOUNT CARMEL'))
    return 'district_hospital';
  return 'district_hospital';
}

/** Official secondary facilities — all start as pending (not yet enrolled / no Hospi OS login used) */
const RAW_LIST: { name: string; location: string }[] = [
  { name: 'Immanuel General Hospital', location: 'Eket' },
  { name: 'General Hospital', location: 'Ikot Ekpene' },
  { name: 'General Hospital', location: 'Iquita Oron' },
  { name: 'Methodist General Hospital', location: 'Ituk Mbang' },
  { name: 'General Hospital', location: 'Etinan' },
  { name: 'General Hospital', location: 'Ukpom Abak' },
  { name: 'General Hospital', location: 'Awa' },
  { name: 'General Hospital', location: 'Ikot Okoro' },
  { name: 'General Hospital', location: 'Ikono' },
  { name: 'General Hospital', location: 'Amammong, Okobo' },
  { name: 'Mount Carmel Hospital', location: 'Akpa Utong' },
  { name: 'General Hospital', location: 'Urue-Offong/Oruko' },
  { name: 'General Hospital', location: 'Ikpe Annang' },
  { name: 'General Hospital', location: 'Ini' },
  { name: 'General Hospital', location: 'Ikot Abasi' },
  { name: 'General Hospital', location: 'Mbioto 2' },
  { name: 'Mary Slessor General Hospital', location: 'Itu' },
  { name: 'General Hospital', location: 'Uruk Ata Ikot Ekpor' },
  { name: 'QIC Leprosy Hospital', location: 'Ekpene Obom' },
  { name: 'Infectious Disease Hospital', location: 'Ikot Ekpene' },
  { name: 'Psychiatric Hospital', location: 'Eket' },
  { name: 'Cottage Hospital', location: 'Ukana' },
  { name: 'Cottage Hospital', location: 'Ibeno' },
  { name: 'Cottage Hospital', location: 'Ikot Abia' },
  { name: 'Cottage Hospital', location: 'Ikot Ekpaw' },
  { name: 'Cottage Hospital', location: 'Asong' },
  { name: 'Cottage Hospital', location: 'Ekpene Obo' },
  { name: 'Cottage Hospital', location: 'Ikot Eko Ibon' },
  { name: 'Cottage Hospital', location: 'Eastern Obolo' },
  { name: 'Cottage Hospital', location: 'Ikot Ekpene Udo' },
  { name: 'Redeemer Cottage Hospital', location: 'Ibesit' },
  { name: 'Cottage Hospital', location: 'Akai Ubium' },
  { name: 'Cottage Hospital', location: 'Ika' },
  { name: 'Comprehensive Health Care Centre', location: 'Nto Edino' },
  { name: 'Comprehensive Health Care Centre', location: 'Mbiaya Uruan' },
];

export function buildOfficialFacilityRegistry(): AkwaIbomFacility[] {
  return RAW_LIST.map((item, idx) => {
    const sn = idx + 1;
    const facilityId = `AKS-SEC-${String(sn).padStart(3, '0')}`;
    const displayName =
      item.name.includes('General Hospital') && item.name === 'General Hospital'
        ? `General Hospital, ${item.location}`
        : `${item.name}, ${item.location}`;

    return {
      facilityId,
      facilityName: displayName,
      location: item.location,
      region: inferRegion(item.location, item.name),
      tier: inferTier(item.name),
      enrollmentStatus: 'pending' as FacilityEnrollmentStatus,
      accreditationStatus: 'pending' as const,
    };
  });
}

/** Generate a one-time Hospi OS credential pair for a facility */
export function generateHospiCredentials(facility: AkwaIbomFacility): {
  hospiLogin: string;
  hospiTempPassword: string;
  issuedAt: string;
} {
  const slug = facility.location
    .replace(/[^a-zA-Z0-9]/g, '')
    .toUpperCase()
    .slice(0, 8);
  const rand = Math.random().toString(36).slice(2, 8).toUpperCase();
  const login = `HOSPI.${slug}.${facility.facilityId.slice(-3)}`;
  const password = `AKS-${rand}-${Date.now().toString(36).slice(-4).toUpperCase()}`;
  return {
    hospiLogin: login,
    hospiTempPassword: password,
    issuedAt: new Date().toISOString(),
  };
}

/** Simulate facility using the generated login → becomes active */
export function activateFacility(
  facility: AkwaIbomFacility
): AkwaIbomFacility {
  const beds = facility.tier === 'cottage_hospital' ? 40 + Math.floor(Math.random() * 40)
    : facility.tier === 'comprehensive_health_centre' ? 60 + Math.floor(Math.random() * 40)
    : facility.tier === 'specialized_center' ? 80 + Math.floor(Math.random() * 60)
    : 120 + Math.floor(Math.random() * 180);

  const occ = Math.floor(beds * (0.55 + Math.random() * 0.35));
  const icuTotal = Math.max(2, Math.floor(beds / 12));
  const icuOcc = Math.floor(icuTotal * (0.5 + Math.random() * 0.4));

  return {
    ...facility,
    enrollmentStatus: 'active',
    activatedAt: new Date().toISOString(),
    lastSeenAt: new Date().toISOString(),
    totalBeds: beds,
    occupiedBeds: occ,
    icuBedsTotal: icuTotal,
    icuBedsOccupied: icuOcc,
    ventilatorsAvailable: Math.floor(Math.random() * 6) + 1,
    staffOnDuty: Math.floor(beds * 0.35) + 20,
    complianceScore: Math.round((82 + Math.random() * 16) * 10) / 10,
    emergencyStatus: 'normal',
    licenseNumber: `MOH-LIC-2026-${facility.facilityId.slice(-3)}`,
    licenseExpires: '2028-12-31',
    accreditationStatus: 'provisional',
  };
}
