export * from './patient';
export * from './appointment';
export * from './tourism';
export * from './clinic';
export * from './os';
export * from './admin';
export * from './banking';
export * from './security';
export * from './sync';
